### ISSUE TITLE
Could you possibly make it any harder to create the environments? Thanks a bunch!

### ISSUE THREAD

**Issue by ietres** [RaymondWang987/VDW_Dataset_Toolkits#1]

**Comment by RaymondWang987** [comment]
1. We release the code for helping future research. If you have any question, you can ask, but nut not being impolite, showing that you are a rude person of low quality.
2. If you do not want to use, just don't use. It's your problem but not mine. 
3. The data construction is hard, involving many steps and repos, how can it be easy to combine GMFlow, SegFormer, and Mask2Former? You can make it but I can. It's not my problem. Thanks!
